-- MySQL Script generated by MySQL Workbench
-- Fri Nov 10 11:15:00 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Proj_DBPY
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `proj_DBPY` ;

-- -----------------------------------------------------
-- Schema Proj_DBPY
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Proj_DBPY` DEFAULT CHARACTER SET utf8 ;
USE `Proj_DBPY` ;

-- -----------------------------------------------------
-- Table `Proj_DBPY`.`Results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Proj_DBPY`.`Results` ;

CREATE TABLE IF NOT EXISTS `Proj_DBPY`.`Results` (
  `idResults` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(45) NULL,
  `date_hour` DATETIME NULL,
  `duration` TIME NULL,
  `exercice`	VARCHAR(45) NULL,
  `nbtrials` INT NULL,
  `nbok` INT NULL,
  `percent` FLOAT NULL,
  PRIMARY KEY (`idResults`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
